SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `ticketdb` DEFAULT CHARACTER SET utf8mb3 ;
USE `ticketdb` ;

CREATE TABLE IF NOT EXISTS `ticketdb`.`users` (
  `userID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `commonName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `passwordHash` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `commonName_UNIQUE` (`commonName` ASC),
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC),
  UNIQUE INDEX `email` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE TABLE IF NOT EXISTS `ticketdb`.`tickets` (
  `ticketID` INT UNSIGNED NOT NULL,
  `users_userID` INT UNSIGNED NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`ticketID`, `users_userID`),
  UNIQUE INDEX `ticketID_UNIQUE` (`ticketID` ASC),
  CONSTRAINT `fk_tickets_users`
    FOREIGN KEY (`users_userID`)
    REFERENCES `ticketdb`.`users` (`userID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
